/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as PublicEventRouteImport } from './routes/_public/event'
import { Route as PublicEventsRouteImport } from './routes/_public/events'
import { Route as PublicForPartnersRouteImport } from './routes/_public/for-partners'
import { Route as PublicHomeRouteImport } from './routes/_public/home'
import { Route as PublicIncubatorRouteImport } from './routes/_public/incubator'
import { Route as PublicInnovationChallengeRouteImport } from './routes/_public/innovation-challenge'
import { Route as PublicStartupsRouteImport } from './routes/_public/startups'
import { Route as ChallengeResourceHubIndexRouteImport } from './routes/challenge-resource-hub/index'
import { Route as ChallengeResourceHubHubRouteImport } from './routes/challenge-resource-hub/_hub'
import { Route as ChallengeResourceHubAuthRouteImport } from './routes/challenge-resource-hub/auth'
import { Route as ChallengeResourceHubHubAiToolkitRouteImport } from './routes/challenge-resource-hub/_hub/ai-toolkit'
import { Route as ChallengeResourceHubHubAttendanceRouteImport } from './routes/challenge-resource-hub/_hub/attendance'
import { Route as ChallengeResourceHubHubBooksRouteImport } from './routes/challenge-resource-hub/_hub/books'
import { Route as ChallengeResourceHubHubCertificationsRouteImport } from './routes/challenge-resource-hub/_hub/certifications'
import { Route as ChallengeResourceHubHubDashboardRouteImport } from './routes/challenge-resource-hub/_hub/dashboard'
import { Route as ChallengeResourceHubHubMyLibraryRouteImport } from './routes/challenge-resource-hub/_hub/my-library'
import { Route as ChallengeResourceHubHubNotesRouteImport } from './routes/challenge-resource-hub/_hub/notes'
import { Route as ChallengeResourceHubHubProgressRouteImport } from './routes/challenge-resource-hub/_hub/progress'
import { Route as ChallengeResourceHubHubResourcesRouteImport } from './routes/challenge-resource-hub/_hub/resources'
import { Route as ChallengeResourceHubHubCategorySlugRouteImport } from './routes/challenge-resource-hub/_hub/category.$slug'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const PublicEventRoute = PublicEventRouteImport.update({
  id: '/event',
  path: '/event',
  getParentRoute: () => PublicRoute,
} as any)
const PublicEventsRoute = PublicEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => PublicRoute,
} as any)
const PublicForPartnersRoute = PublicForPartnersRouteImport.update({
  id: '/for-partners',
  path: '/for-partners',
  getParentRoute: () => PublicRoute,
} as any)
const PublicHomeRoute = PublicHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => PublicRoute,
} as any)
const PublicIncubatorRoute = PublicIncubatorRouteImport.update({
  id: '/incubator',
  path: '/incubator',
  getParentRoute: () => PublicRoute,
} as any)
const PublicInnovationChallengeRoute =
  PublicInnovationChallengeRouteImport.update({
    id: '/innovation-challenge',
    path: '/innovation-challenge',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicStartupsRoute = PublicStartupsRouteImport.update({
  id: '/startups',
  path: '/startups',
  getParentRoute: () => PublicRoute,
} as any)
const ChallengeResourceHubIndexRoute =
  ChallengeResourceHubIndexRouteImport.update({
    id: '/challenge-resource-hub/',
    path: '/challenge-resource-hub/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ChallengeResourceHubHubRoute = ChallengeResourceHubHubRouteImport.update({
  id: '/challenge-resource-hub/_hub',
  path: '/challenge-resource-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengeResourceHubAuthRoute =
  ChallengeResourceHubAuthRouteImport.update({
    id: '/challenge-resource-hub/auth',
    path: '/challenge-resource-hub/auth',
    getParentRoute: () => rootRouteImport,
  } as any)
const ChallengeResourceHubHubAiToolkitRoute =
  ChallengeResourceHubHubAiToolkitRouteImport.update({
    id: '/ai-toolkit',
    path: '/ai-toolkit',
    getParentRoute: () => ChallengeResourceHubHubRoute,
  } as any)
const ChallengeResourceHubHubAttendanceRoute =
  ChallengeResourceHubHubAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => ChallengeResourceHubHubRoute,
  } as any)
const ChallengeResourceHubHubBooksRoute =
  ChallengeResourceHubHubBooksRouteImport.update({
    id: '/books',
    path: '/books',
    getParentRoute: () => ChallengeResourceHubHubRoute,
  } as any)
const ChallengeResourceHubHubCertificationsRoute =
  ChallengeResourceHubHubCertificationsRouteImport.update({
    id: '/certifications',
    path: '/certifications',
    getParentRoute: () => ChallengeResourceHubHubRoute,
  } as any)
const ChallengeResourceHubHubDashboardRoute =
  ChallengeResourceHubHubDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => ChallengeResourceHubHubRoute,
  } as any)
const ChallengeResourceHubHubMyLibraryRoute =
  ChallengeResourceHubHubMyLibraryRouteImport.update({
    id: '/my-library',
    path: '/my-library',
    getParentRoute: () => ChallengeResourceHubHubRoute,
  } as any)
const ChallengeResourceHubHubNotesRoute =
  ChallengeResourceHubHubNotesRouteImport.update({
    id: '/notes',
    path: '/notes',
    getParentRoute: () => ChallengeResourceHubHubRoute,
  } as any)
const ChallengeResourceHubHubProgressRoute =
  ChallengeResourceHubHubProgressRouteImport.update({
    id: '/progress',
    path: '/progress',
    getParentRoute: () => ChallengeResourceHubHubRoute,
  } as any)
const ChallengeResourceHubHubResourcesRoute =
  ChallengeResourceHubHubResourcesRouteImport.update({
    id: '/resources',
    path: '/resources',
    getParentRoute: () => ChallengeResourceHubHubRoute,
  } as any)
const ChallengeResourceHubHubCategorySlugRoute =
  ChallengeResourceHubHubCategorySlugRouteImport.update({
    id: '/category/$slug',
    path: '/category/$slug',
    getParentRoute: () => ChallengeResourceHubHubRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/about': typeof PublicAboutRoute
  '/event': typeof PublicEventRoute
  '/events': typeof PublicEventsRoute
  '/for-partners': typeof PublicForPartnersRoute
  '/home': typeof PublicHomeRoute
  '/incubator': typeof PublicIncubatorRoute
  '/innovation-challenge': typeof PublicInnovationChallengeRoute
  '/startups': typeof PublicStartupsRoute
  '/challenge-resource-hub': typeof ChallengeResourceHubHubRouteWithChildren
  '/challenge-resource-hub/auth': typeof ChallengeResourceHubAuthRoute
  '/challenge-resource-hub/': typeof ChallengeResourceHubIndexRoute
  '/challenge-resource-hub/ai-toolkit': typeof ChallengeResourceHubHubAiToolkitRoute
  '/challenge-resource-hub/attendance': typeof ChallengeResourceHubHubAttendanceRoute
  '/challenge-resource-hub/books': typeof ChallengeResourceHubHubBooksRoute
  '/challenge-resource-hub/certifications': typeof ChallengeResourceHubHubCertificationsRoute
  '/challenge-resource-hub/dashboard': typeof ChallengeResourceHubHubDashboardRoute
  '/challenge-resource-hub/my-library': typeof ChallengeResourceHubHubMyLibraryRoute
  '/challenge-resource-hub/notes': typeof ChallengeResourceHubHubNotesRoute
  '/challenge-resource-hub/progress': typeof ChallengeResourceHubHubProgressRoute
  '/challenge-resource-hub/resources': typeof ChallengeResourceHubHubResourcesRoute
  '/challenge-resource-hub/category/$slug': typeof ChallengeResourceHubHubCategorySlugRoute
}
export interface FileRoutesByTo {
  '/about': typeof PublicAboutRoute
  '/event': typeof PublicEventRoute
  '/events': typeof PublicEventsRoute
  '/for-partners': typeof PublicForPartnersRoute
  '/home': typeof PublicHomeRoute
  '/incubator': typeof PublicIncubatorRoute
  '/innovation-challenge': typeof PublicInnovationChallengeRoute
  '/startups': typeof PublicStartupsRoute
  '/challenge-resource-hub': typeof ChallengeResourceHubIndexRoute
  '/challenge-resource-hub/auth': typeof ChallengeResourceHubAuthRoute
  '/': typeof PublicIndexRoute
  '/challenge-resource-hub/ai-toolkit': typeof ChallengeResourceHubHubAiToolkitRoute
  '/challenge-resource-hub/attendance': typeof ChallengeResourceHubHubAttendanceRoute
  '/challenge-resource-hub/books': typeof ChallengeResourceHubHubBooksRoute
  '/challenge-resource-hub/certifications': typeof ChallengeResourceHubHubCertificationsRoute
  '/challenge-resource-hub/dashboard': typeof ChallengeResourceHubHubDashboardRoute
  '/challenge-resource-hub/my-library': typeof ChallengeResourceHubHubMyLibraryRoute
  '/challenge-resource-hub/notes': typeof ChallengeResourceHubHubNotesRoute
  '/challenge-resource-hub/progress': typeof ChallengeResourceHubHubProgressRoute
  '/challenge-resource-hub/resources': typeof ChallengeResourceHubHubResourcesRoute
  '/challenge-resource-hub/category/$slug': typeof ChallengeResourceHubHubCategorySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/_public/about': typeof PublicAboutRoute
  '/_public/event': typeof PublicEventRoute
  '/_public/events': typeof PublicEventsRoute
  '/_public/for-partners': typeof PublicForPartnersRoute
  '/_public/home': typeof PublicHomeRoute
  '/_public/incubator': typeof PublicIncubatorRoute
  '/_public/innovation-challenge': typeof PublicInnovationChallengeRoute
  '/_public/startups': typeof PublicStartupsRoute
  '/challenge-resource-hub/_hub': typeof ChallengeResourceHubHubRouteWithChildren
  '/challenge-resource-hub/auth': typeof ChallengeResourceHubAuthRoute
  '/_public/': typeof PublicIndexRoute
  '/challenge-resource-hub/': typeof ChallengeResourceHubIndexRoute
  '/challenge-resource-hub/_hub/ai-toolkit': typeof ChallengeResourceHubHubAiToolkitRoute
  '/challenge-resource-hub/_hub/attendance': typeof ChallengeResourceHubHubAttendanceRoute
  '/challenge-resource-hub/_hub/books': typeof ChallengeResourceHubHubBooksRoute
  '/challenge-resource-hub/_hub/certifications': typeof ChallengeResourceHubHubCertificationsRoute
  '/challenge-resource-hub/_hub/dashboard': typeof ChallengeResourceHubHubDashboardRoute
  '/challenge-resource-hub/_hub/my-library': typeof ChallengeResourceHubHubMyLibraryRoute
  '/challenge-resource-hub/_hub/notes': typeof ChallengeResourceHubHubNotesRoute
  '/challenge-resource-hub/_hub/progress': typeof ChallengeResourceHubHubProgressRoute
  '/challenge-resource-hub/_hub/resources': typeof ChallengeResourceHubHubResourcesRoute
  '/challenge-resource-hub/_hub/category/$slug': typeof ChallengeResourceHubHubCategorySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/event'
    | '/events'
    | '/for-partners'
    | '/home'
    | '/incubator'
    | '/innovation-challenge'
    | '/startups'
    | '/challenge-resource-hub'
    | '/challenge-resource-hub/auth'
    | '/challenge-resource-hub/'
    | '/challenge-resource-hub/ai-toolkit'
    | '/challenge-resource-hub/attendance'
    | '/challenge-resource-hub/books'
    | '/challenge-resource-hub/certifications'
    | '/challenge-resource-hub/dashboard'
    | '/challenge-resource-hub/my-library'
    | '/challenge-resource-hub/notes'
    | '/challenge-resource-hub/progress'
    | '/challenge-resource-hub/resources'
    | '/challenge-resource-hub/category/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/event'
    | '/events'
    | '/for-partners'
    | '/home'
    | '/incubator'
    | '/innovation-challenge'
    | '/startups'
    | '/challenge-resource-hub'
    | '/challenge-resource-hub/auth'
    | '/'
    | '/challenge-resource-hub/ai-toolkit'
    | '/challenge-resource-hub/attendance'
    | '/challenge-resource-hub/books'
    | '/challenge-resource-hub/certifications'
    | '/challenge-resource-hub/dashboard'
    | '/challenge-resource-hub/my-library'
    | '/challenge-resource-hub/notes'
    | '/challenge-resource-hub/progress'
    | '/challenge-resource-hub/resources'
    | '/challenge-resource-hub/category/$slug'
  id:
    | '__root__'
    | '/_public'
    | '/_public/about'
    | '/_public/event'
    | '/_public/events'
    | '/_public/for-partners'
    | '/_public/home'
    | '/_public/incubator'
    | '/_public/innovation-challenge'
    | '/_public/startups'
    | '/challenge-resource-hub/_hub'
    | '/challenge-resource-hub/auth'
    | '/_public/'
    | '/challenge-resource-hub/'
    | '/challenge-resource-hub/_hub/ai-toolkit'
    | '/challenge-resource-hub/_hub/attendance'
    | '/challenge-resource-hub/_hub/books'
    | '/challenge-resource-hub/_hub/certifications'
    | '/challenge-resource-hub/_hub/dashboard'
    | '/challenge-resource-hub/_hub/my-library'
    | '/challenge-resource-hub/_hub/notes'
    | '/challenge-resource-hub/_hub/progress'
    | '/challenge-resource-hub/_hub/resources'
    | '/challenge-resource-hub/_hub/category/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  ChallengeResourceHubHubRoute: typeof ChallengeResourceHubHubRouteWithChildren
  ChallengeResourceHubAuthRoute: typeof ChallengeResourceHubAuthRoute
  ChallengeResourceHubIndexRoute: typeof ChallengeResourceHubIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/event': {
      id: '/_public/event'
      path: '/event'
      fullPath: '/event'
      preLoaderRoute: typeof PublicEventRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/events': {
      id: '/_public/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof PublicEventsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/for-partners': {
      id: '/_public/for-partners'
      path: '/for-partners'
      fullPath: '/for-partners'
      preLoaderRoute: typeof PublicForPartnersRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/home': {
      id: '/_public/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof PublicHomeRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/incubator': {
      id: '/_public/incubator'
      path: '/incubator'
      fullPath: '/incubator'
      preLoaderRoute: typeof PublicIncubatorRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/innovation-challenge': {
      id: '/_public/innovation-challenge'
      path: '/innovation-challenge'
      fullPath: '/innovation-challenge'
      preLoaderRoute: typeof PublicInnovationChallengeRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/startups': {
      id: '/_public/startups'
      path: '/startups'
      fullPath: '/startups'
      preLoaderRoute: typeof PublicStartupsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/challenge-resource-hub/': {
      id: '/challenge-resource-hub/'
      path: '/challenge-resource-hub'
      fullPath: '/challenge-resource-hub/'
      preLoaderRoute: typeof ChallengeResourceHubIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenge-resource-hub/_hub': {
      id: '/challenge-resource-hub/_hub'
      path: '/challenge-resource-hub'
      fullPath: '/challenge-resource-hub'
      preLoaderRoute: typeof ChallengeResourceHubHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenge-resource-hub/auth': {
      id: '/challenge-resource-hub/auth'
      path: '/challenge-resource-hub/auth'
      fullPath: '/challenge-resource-hub/auth'
      preLoaderRoute: typeof ChallengeResourceHubAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenge-resource-hub/_hub/ai-toolkit': {
      id: '/challenge-resource-hub/_hub/ai-toolkit'
      path: '/ai-toolkit'
      fullPath: '/challenge-resource-hub/ai-toolkit'
      preLoaderRoute: typeof ChallengeResourceHubHubAiToolkitRouteImport
      parentRoute: typeof ChallengeResourceHubHubRoute
    }
    '/challenge-resource-hub/_hub/attendance': {
      id: '/challenge-resource-hub/_hub/attendance'
      path: '/attendance'
      fullPath: '/challenge-resource-hub/attendance'
      preLoaderRoute: typeof ChallengeResourceHubHubAttendanceRouteImport
      parentRoute: typeof ChallengeResourceHubHubRoute
    }
    '/challenge-resource-hub/_hub/books': {
      id: '/challenge-resource-hub/_hub/books'
      path: '/books'
      fullPath: '/challenge-resource-hub/books'
      preLoaderRoute: typeof ChallengeResourceHubHubBooksRouteImport
      parentRoute: typeof ChallengeResourceHubHubRoute
    }
    '/challenge-resource-hub/_hub/certifications': {
      id: '/challenge-resource-hub/_hub/certifications'
      path: '/certifications'
      fullPath: '/challenge-resource-hub/certifications'
      preLoaderRoute: typeof ChallengeResourceHubHubCertificationsRouteImport
      parentRoute: typeof ChallengeResourceHubHubRoute
    }
    '/challenge-resource-hub/_hub/dashboard': {
      id: '/challenge-resource-hub/_hub/dashboard'
      path: '/dashboard'
      fullPath: '/challenge-resource-hub/dashboard'
      preLoaderRoute: typeof ChallengeResourceHubHubDashboardRouteImport
      parentRoute: typeof ChallengeResourceHubHubRoute
    }
    '/challenge-resource-hub/_hub/my-library': {
      id: '/challenge-resource-hub/_hub/my-library'
      path: '/my-library'
      fullPath: '/challenge-resource-hub/my-library'
      preLoaderRoute: typeof ChallengeResourceHubHubMyLibraryRouteImport
      parentRoute: typeof ChallengeResourceHubHubRoute
    }
    '/challenge-resource-hub/_hub/notes': {
      id: '/challenge-resource-hub/_hub/notes'
      path: '/notes'
      fullPath: '/challenge-resource-hub/notes'
      preLoaderRoute: typeof ChallengeResourceHubHubNotesRouteImport
      parentRoute: typeof ChallengeResourceHubHubRoute
    }
    '/challenge-resource-hub/_hub/progress': {
      id: '/challenge-resource-hub/_hub/progress'
      path: '/progress'
      fullPath: '/challenge-resource-hub/progress'
      preLoaderRoute: typeof ChallengeResourceHubHubProgressRouteImport
      parentRoute: typeof ChallengeResourceHubHubRoute
    }
    '/challenge-resource-hub/_hub/resources': {
      id: '/challenge-resource-hub/_hub/resources'
      path: '/resources'
      fullPath: '/challenge-resource-hub/resources'
      preLoaderRoute: typeof ChallengeResourceHubHubResourcesRouteImport
      parentRoute: typeof ChallengeResourceHubHubRoute
    }
    '/challenge-resource-hub/_hub/category/$slug': {
      id: '/challenge-resource-hub/_hub/category/$slug'
      path: '/category/$slug'
      fullPath: '/challenge-resource-hub/category/$slug'
      preLoaderRoute: typeof ChallengeResourceHubHubCategorySlugRouteImport
      parentRoute: typeof ChallengeResourceHubHubRoute
    }
  }
}

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicEventRoute: typeof PublicEventRoute
  PublicEventsRoute: typeof PublicEventsRoute
  PublicForPartnersRoute: typeof PublicForPartnersRoute
  PublicHomeRoute: typeof PublicHomeRoute
  PublicIncubatorRoute: typeof PublicIncubatorRoute
  PublicInnovationChallengeRoute: typeof PublicInnovationChallengeRoute
  PublicStartupsRoute: typeof PublicStartupsRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicEventRoute: PublicEventRoute,
  PublicEventsRoute: PublicEventsRoute,
  PublicForPartnersRoute: PublicForPartnersRoute,
  PublicHomeRoute: PublicHomeRoute,
  PublicIncubatorRoute: PublicIncubatorRoute,
  PublicInnovationChallengeRoute: PublicInnovationChallengeRoute,
  PublicStartupsRoute: PublicStartupsRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface ChallengeResourceHubHubRouteChildren {
  ChallengeResourceHubHubAiToolkitRoute: typeof ChallengeResourceHubHubAiToolkitRoute
  ChallengeResourceHubHubAttendanceRoute: typeof ChallengeResourceHubHubAttendanceRoute
  ChallengeResourceHubHubBooksRoute: typeof ChallengeResourceHubHubBooksRoute
  ChallengeResourceHubHubCertificationsRoute: typeof ChallengeResourceHubHubCertificationsRoute
  ChallengeResourceHubHubDashboardRoute: typeof ChallengeResourceHubHubDashboardRoute
  ChallengeResourceHubHubMyLibraryRoute: typeof ChallengeResourceHubHubMyLibraryRoute
  ChallengeResourceHubHubNotesRoute: typeof ChallengeResourceHubHubNotesRoute
  ChallengeResourceHubHubProgressRoute: typeof ChallengeResourceHubHubProgressRoute
  ChallengeResourceHubHubResourcesRoute: typeof ChallengeResourceHubHubResourcesRoute
  ChallengeResourceHubHubCategorySlugRoute: typeof ChallengeResourceHubHubCategorySlugRoute
}

const ChallengeResourceHubHubRouteChildren: ChallengeResourceHubHubRouteChildren =
  {
    ChallengeResourceHubHubAiToolkitRoute:
      ChallengeResourceHubHubAiToolkitRoute,
    ChallengeResourceHubHubAttendanceRoute:
      ChallengeResourceHubHubAttendanceRoute,
    ChallengeResourceHubHubBooksRoute: ChallengeResourceHubHubBooksRoute,
    ChallengeResourceHubHubCertificationsRoute:
      ChallengeResourceHubHubCertificationsRoute,
    ChallengeResourceHubHubDashboardRoute:
      ChallengeResourceHubHubDashboardRoute,
    ChallengeResourceHubHubMyLibraryRoute:
      ChallengeResourceHubHubMyLibraryRoute,
    ChallengeResourceHubHubNotesRoute: ChallengeResourceHubHubNotesRoute,
    ChallengeResourceHubHubProgressRoute: ChallengeResourceHubHubProgressRoute,
    ChallengeResourceHubHubResourcesRoute:
      ChallengeResourceHubHubResourcesRoute,
    ChallengeResourceHubHubCategorySlugRoute:
      ChallengeResourceHubHubCategorySlugRoute,
  }

const ChallengeResourceHubHubRouteWithChildren =
  ChallengeResourceHubHubRoute._addFileChildren(
    ChallengeResourceHubHubRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  ChallengeResourceHubHubRoute: ChallengeResourceHubHubRouteWithChildren,
  ChallengeResourceHubAuthRoute: ChallengeResourceHubAuthRoute,
  ChallengeResourceHubIndexRoute: ChallengeResourceHubIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
